name: Build, Push and Deploy Docker Image
run-name: Build, Push and Deploy Image
on: [push]
env: 
 IMAGE_NAME: "ghcr.io/develz12/nginx-julang"
jobs: 
 build-push-image:
  runs-on: ubuntu-latest
  steps: 
   - name: Check out repository code 
     uses: actions/checkout@v4
   - name: Build Image
     run: docker build -t $IMAGE_NAME .
   - name: List Image
     run: docker images
   - name: Login to Github Registry
     run: echo ${{secrets.TOKEN_DVLZ3}} | docker login ghcr.io -u develz --password-stdin
   - name: Push Image
     run: docker push $IMAGE_NAME
  
  deploy: 
   needs: build-push-image
   runs-on: ubuntu-latest
   steps: 
    - name: Checkout out repository code
      uses: actions/checkout@v4
    - name: Login to GitHub registry
      run: echo ${{secrets.TOKEN_DVLZ3}} | docker login ghcr.io -u develz --password-stdin
    - name: stop and remove existing container
      run: docker-compose down --rmi all
    - name: start container 
      run: docker-compose up -d
    - name: view container
      run: docker-compose ps
    - name: check container
      run: curl localhost:8080
